### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [skeithtan/falcon#1]
Hi. I am a graphic designer. I would like to volunteer to design a logo for this repository that you can use in the readme file. What do you say?

**Comment by skeithtan** [comment]
That sounds great! Just keep in mind though that it may change in the future, and I might not be able to put it in the actual app itself. I'd like to see the logo though, if you're up for it.

**Comment by batarian71** [comment]
I designed a logo like this for you. Is there anything you want to add ? Which one do you prefer ?
![falcon](https://user-images.githubusercontent.com/36008612/42384841-c7dd7cf2-8143-11e8-85c8-4cc0eec3b029.jpg)

**Comment by skeithtan** [comment]
Falcons official font is Raleway, font weight 600. Can we see that?

Also, monochrome would be better, and not shaded. Bottom left looks great.

**Comment by skeithtan** [comment]
Lowercase everything, except for F. Try to make the logo the same height as the F. Then make the font bold too. 

Looking great!

**Comment by batarian71** [comment]
Of course

**Comment by batarian71** [comment]
What do you think?
![falcon](https://user-images.githubusercontent.com/36008612/42404162-a5053232-818f-11e8-9a5c-94e5a30e8834.jpg)

**Comment by skeithtan** [comment]
Great, but the font doesn't look quite like [Raleway](https://fonts.google.com/specimen/Raleway), and the font is too thin.

**Comment by batarian71** [comment]
I forgot to thicken the font.
![falcon](https://user-images.githubusercontent.com/36008612/42404273-5fe7b0e8-8190-11e8-85fb-0a006b606de8.jpg)

**Comment by skeithtan** [comment]
Are you sure the font is Raleway? This doesn't look like Raleway.

**Comment by batarian71** [comment]
Can you really link to Raleway?

**Comment by skeithtan** [comment]
https://fonts.google.com/specimen/Raleway

**Comment by batarian71** [comment]
I think it was.
![falcon](https://user-images.githubusercontent.com/36008612/42404596-3f421cd6-8193-11e8-8e16-8143ae48263d.jpg)

**Comment by skeithtan** [comment]
Ah, that's better. If you could make it bolder, I'll place that in the `readme.md`. 

Thanks for the help!

**Comment by skeithtan** [comment]
Merged. Thanks for the logo!
